import { parseAndReflect } from "./parsePhoneData";
import type {
  DailyNote,
  MemoryCapsule,
  ReminderSuggestion,
  WeeklyLetter,
} from "./types";

/** v2: reflections generated by parsing Ella's shared phone data */

let cached: ReturnType<typeof parseAndReflect> | null = null;

function getParsed() {
  if (!cached) cached = parseAndReflect();
  return cached;
}

export function getParsedWeek() {
  return getParsed();
}

export function getDailyNote(): DailyNote {
  return getParsed().dailyNote;
}

export function getReminderSuggestion(): ReminderSuggestion {
  return getParsed().reminder;
}

export function getWeeklyLetter(): WeeklyLetter {
  return getParsed().weeklyLetter;
}

export function getMemoryCapsule(): MemoryCapsule {
  return getParsed().capsule;
}

export function resetParsedCache() {
  cached = null;
}
