import type { MemorySignal, UserProfile } from "./types";

export const WEEK_START = "2026-02-17";
export const WEEK_TITLE = "Campus Week";

export const ellaProfile: UserProfile = {
  id: "ella",
  name: "Ella",
  vibePreferences: [
    "warm",
    "cinematic",
    "soft",
    "nostalgic",
    "slightly playful",
    "poetic but grounded",
  ],
  noticePreferences: [
    "tiny joys",
    "friendships",
    "routines",
    "places",
    "solo moments",
    "songs",
  ],
  signalPermissions: {
    photos: true,
    texts: true,
    calendar: true,
    places: true,
    songs: true,
    reflections: true,
    friend_memories: true,
  },
  noteFrequency: "weekly memory letters",
  tonePreference: "warm",
};

export const florenceWeek3Signals: MemorySignal[] = [
  // Day 1 — Monday
  {
    id: "sig-mon-photo-cafe",
    type: "photo",
    timestamp: "2026-02-17T15:30:00Z",
    source: "saved photo",
    title: "Cappuccino and journal after class",
    summary: "A quiet table by the window at the cafe near class.",
    emotionalTags: ["peaceful", "solo", "cozy"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    caption: "cappuccino, journal, the little table by the window",
    location: "Cafe near class, Florence",
    userNote: "Being alone did not feel lonely today.",
  },
  {
    id: "sig-mon-place-cafe",
    type: "place_visit",
    timestamp: "2026-02-17T14:45:00Z",
    source: "manual check-in",
    title: "Cafe near class",
    summary: "48 minutes at your after-class spot.",
    emotionalTags: ["routine", "peaceful"],
    privacyLevel: "private",
    placeName: "Cafe near class",
    location: "Florence",
    durationMinutes: 48,
    tags: ["after class", "journal"],
    userSaved: true,
  },
  {
    id: "sig-mon-song-sweet",
    type: "song_played",
    timestamp: "2026-02-17T17:10:00Z",
    source: "song you added",
    title: "Sweet Disposition",
    summary: "Played while walking home from class.",
    emotionalTags: ["walk", "golden hour"],
    privacyLevel: "private",
    songTitle: "Sweet Disposition",
    artist: "The Temper Trap",
    context: "walk home",
    repeatCountThisWeek: 2,
  },
  {
    id: "sig-mon-reflection-solo",
    type: "reflection",
    timestamp: "2026-02-17T18:00:00Z",
    source: "tiny reflection",
    title: "On being alone today",
    summary: "You wrote about solo time feeling good.",
    emotionalTags: ["solo", "grounded"],
    privacyLevel: "private",
    prompt: "How did today feel?",
    answer: "I liked being alone today. It didn't feel lonely.",
  },
  // Day 2 — Tuesday
  {
    id: "sig-tue-calendar-lecture",
    type: "calendar_event",
    timestamp: "2026-02-18T10:00:00Z",
    source: "calendar moment",
    title: "Renaissance Art lecture",
    summary: "Morning lecture before the museum visit.",
    emotionalTags: ["learning", "curious"],
    privacyLevel: "private",
    eventTitle: "Renaissance Art lecture",
    location: "Florence",
    category: "class",
    description: "Notes on light in early Renaissance panels.",
  },
  {
    id: "sig-tue-photo-uffizi",
    type: "photo",
    timestamp: "2026-02-18T14:20:00Z",
    source: "saved photo",
    title: "Museum hallway with soft light",
    summary: "A quiet corridor at the Uffizi.",
    emotionalTags: ["peaceful", "cinematic"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80",
    location: "Uffizi Gallery",
    userNote: "The quiet parts felt like little pockets of peace.",
  },
  {
    id: "sig-tue-place-uffizi",
    type: "place_visit",
    timestamp: "2026-02-18T13:00:00Z",
    source: "manual check-in",
    title: "Uffizi Gallery",
    summary: "Afternoon wandering the galleries.",
    emotionalTags: ["peaceful", "solo"],
    privacyLevel: "private",
    placeName: "Uffizi Gallery",
    location: "Florence",
    durationMinutes: 120,
    tags: ["art", "museum"],
    userSaved: true,
  },
  {
    id: "sig-tue-reflection-museum",
    type: "reflection",
    timestamp: "2026-02-18T16:30:00Z",
    source: "tiny reflection",
    title: "Museum quiet",
    summary: "Peace in the slower corners of the museum.",
    emotionalTags: ["peaceful", "solo"],
    privacyLevel: "private",
    prompt: "What stayed with you?",
    answer:
      "The quiet parts of the museum felt like little pockets of peace.",
  },
  // Day 3 — Wednesday
  {
    id: "sig-wed-calendar-dinner",
    type: "calendar_event",
    timestamp: "2026-02-19T19:00:00Z",
    source: "calendar moment",
    title: "Dinner with Maya and Andrea",
    summary: "Evening dinner in the city center.",
    emotionalTags: ["friendship", "warm"],
    privacyLevel: "private",
    eventTitle: "Dinner with Maya and Andrea",
    location: "Florence",
    people: ["Maya", "Andrea"],
    category: "social",
  },
  {
    id: "sig-wed-photo-dinner",
    type: "photo",
    timestamp: "2026-02-19T20:15:00Z",
    source: "saved photo",
    title: "Friends laughing at dinner",
    summary: "Maya and Andrea at a small trattoria table.",
    emotionalTags: ["joy", "friendship"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    location: "Florence",
    people: ["Maya", "Andrea"],
  },
  {
    id: "sig-wed-friend-lost-street",
    type: "friend_memory",
    timestamp: "2026-02-19T22:00:00Z",
    source: "friend memory you wrote",
    title: "Getting lost, finding something pretty",
    summary: "A walk home that became an adventure.",
    emotionalTags: ["friendship", "playful"],
    privacyLevel: "private",
    people: ["Maya", "Andrea"],
    memory:
      "We got lost walking home and somehow found the prettiest street.",
    relationshipTag: "study abroad friends",
  },
  {
    id: "sig-wed-song-dreams",
    type: "song_played",
    timestamp: "2026-02-19T22:30:00Z",
    source: "song you added",
    title: "Dreams",
    summary: "Played on the walk back.",
    emotionalTags: ["nostalgic"],
    privacyLevel: "private",
    songTitle: "Dreams",
    artist: "The Cranberries",
    context: "walk home with friends",
  },
  // Day 4 — Thursday
  {
    id: "sig-thu-photo-rain",
    type: "photo",
    timestamp: "2026-02-20T11:00:00Z",
    source: "saved photo",
    title: "Rainy window view",
    summary: "Rain on the glass, everything slower.",
    emotionalTags: ["peaceful", "cozy", "solo"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1421930866250-aa9394e00504?w=800&q=80",
    location: "Apartment, Florence",
    userNote: "Marked as peaceful.",
  },
  {
    id: "sig-thu-place-bookstore",
    type: "place_visit",
    timestamp: "2026-02-20T14:00:00Z",
    source: "manual check-in",
    title: "Tiny bookstore",
    summary: "Sheltered from the rain among old paperbacks.",
    emotionalTags: ["cozy", "peaceful"],
    privacyLevel: "private",
    placeName: "Tiny bookstore",
    location: "Florence",
    durationMinutes: 55,
    tags: ["rain day", "reading"],
    userSaved: true,
  },
  {
    id: "sig-thu-reflection-rain",
    type: "reflection",
    timestamp: "2026-02-20T17:00:00Z",
    source: "tiny reflection",
    title: "Rain day feeling",
    summary: "Slower pace felt good.",
    emotionalTags: ["peaceful", "grounded"],
    privacyLevel: "private",
    prompt: "How did the rain change the day?",
    answer: "The rain made everything feel slower in a good way.",
  },
  {
    id: "sig-thu-song-mystery",
    type: "song_played",
    timestamp: "2026-02-20T18:30:00Z",
    source: "song you added",
    title: "Mystery of Love",
    summary: "Soft soundtrack for a rainy evening.",
    emotionalTags: ["cinematic", "soft"],
    privacyLevel: "private",
    songTitle: "Mystery of Love",
    artist: "Sufjan Stevens",
    context: "rainy evening",
  },
  // Day 5 — Friday
  {
    id: "sig-fri-photo-arno",
    type: "photo",
    timestamp: "2026-02-21T16:45:00Z",
    source: "saved photo",
    title: "Arno river at golden hour",
    summary: "Light on the water, peaceful walk.",
    emotionalTags: ["peaceful", "golden hour", "solo"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&q=80",
    location: "Arno river, Florence",
    userNote: "Marked as peaceful.",
  },
  {
    id: "sig-fri-place-arno",
    type: "place_visit",
    timestamp: "2026-02-21T16:30:00Z",
    source: "manual check-in",
    title: "Arno river walk",
    summary: "Golden-hour walk by the river.",
    emotionalTags: ["peaceful", "routine"],
    privacyLevel: "private",
    placeName: "Arno river walk",
    location: "Florence",
    durationMinutes: 40,
    tags: ["golden hour", "walk"],
    userSaved: true,
  },
  {
    id: "sig-fri-song-sweet-2",
    type: "song_played",
    timestamp: "2026-02-21T17:15:00Z",
    source: "song you added",
    title: "Sweet Disposition",
    summary: "Again on the walk home — becoming a pattern.",
    emotionalTags: ["walk", "peaceful"],
    privacyLevel: "private",
    songTitle: "Sweet Disposition",
    artist: "The Temper Trap",
    context: "Arno walk home",
    repeatCountThisWeek: 2,
  },
  {
    id: "sig-fri-routine-arno",
    type: "routine",
    timestamp: "2026-02-21T17:30:00Z",
    source: "pattern detected",
    title: "Golden-hour Arno walks",
    summary: "Two peaceful walks by the Arno this week.",
    emotionalTags: ["routine", "peaceful"],
    privacyLevel: "private",
    routineName: "Golden-hour walk by the Arno",
    evidence: ["sig-fri-place-arno", "sig-wed-friend-lost-street"],
    frequency: "twice this week",
    suggestion: "Want a gentle reminder tomorrow around 5:15?",
  },
  {
    id: "sig-fri-reminder-arno",
    type: "reminder",
    timestamp: "2026-02-21T17:35:00Z",
    source: "suggestion",
    title: "Golden-hour walk reminder",
    summary: "Soft reminder for tomorrow's Arno walk.",
    emotionalTags: ["gentle"],
    privacyLevel: "private",
    reminderTitle: "Want to make this a ritual?",
    reminderBody:
      "You've gone on a golden-hour walk by the Arno twice this week, and both days had photos you marked as peaceful.",
    suggestedTime: "tomorrow at 5:15",
    relatedSignals: ["sig-fri-photo-arno", "sig-fri-place-arno"],
  },
  // Day 6 — Saturday
  {
    id: "sig-sat-calendar-pastries",
    type: "calendar_event",
    timestamp: "2026-02-22T10:30:00Z",
    source: "calendar moment",
    title: "Pastries with Andrea",
    summary: "Morning pastries at a tiny bakery.",
    emotionalTags: ["friendship", "joy"],
    privacyLevel: "private",
    eventTitle: "Pastries with Andrea",
    location: "Florence",
    people: ["Andrea"],
    category: "social",
  },
  {
    id: "sig-sat-photo-pastry",
    type: "photo",
    timestamp: "2026-02-22T11:00:00Z",
    source: "saved photo",
    title: "Pastry from tiny bakery",
    summary: "Cream and sugar at the smallest table.",
    emotionalTags: ["joy", "friendship"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    location: "Tiny bakery, Florence",
    people: ["Andrea"],
  },
  {
    id: "sig-sat-friend-andrea-tables",
    type: "friend_memory",
    timestamp: "2026-02-22T11:30:00Z",
    source: "friend memory you wrote",
    title: "Smallest tables",
    summary: "A tiny ritual with Andrea.",
    emotionalTags: ["friendship", "playful"],
    privacyLevel: "private",
    people: ["Andrea"],
    memory:
      "Andrea and I laughed about how we always accidentally choose the smallest tables.",
    relationshipTag: "study abroad friend",
  },
  {
    id: "sig-sat-song-pink",
    type: "song_played",
    timestamp: "2026-02-22T12:00:00Z",
    source: "song you added",
    title: "Pink + White",
    summary: "Walking back from the bakery.",
    emotionalTags: ["warm", "soft"],
    privacyLevel: "private",
    songTitle: "Pink + White",
    artist: "Frank Ocean",
    context: "walk from bakery",
  },
  // Day 7 — Sunday (today for demo)
  {
    id: "sig-sun-photo-desk",
    type: "photo",
    timestamp: "2026-02-23T19:00:00Z",
    source: "saved photo",
    title: "Messy desk with postcards",
    summary: "Postcards, pens, the quiet end of the week.",
    emotionalTags: ["nostalgic", "reflective"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80",
    location: "Apartment, Florence",
  },
  {
    id: "sig-sun-reflection-week",
    type: "reflection",
    timestamp: "2026-02-23T20:00:00Z",
    source: "tiny reflection",
    title: "End of the week",
    summary: "Small week, big feeling.",
    emotionalTags: ["nostalgic", "reflective"],
    privacyLevel: "private",
    prompt: "How did this week feel?",
    answer: "This week felt small, but I think I'll miss it.",
  },
  {
    id: "sig-sun-place-cafe-3",
    type: "place_visit",
    timestamp: "2026-02-23T15:00:00Z",
    source: "manual check-in",
    title: "Cafe near class",
    summary: "Third cafe visit this week — a ritual forming.",
    emotionalTags: ["routine", "peaceful", "solo"],
    privacyLevel: "private",
    placeName: "Cafe near class",
    location: "Florence",
    durationMinutes: 52,
    tags: ["after class", "journal"],
    userSaved: true,
  },
  {
    id: "sig-sun-photo-cafe-3",
    type: "photo",
    timestamp: "2026-02-23T15:20:00Z",
    source: "saved photo",
    title: "Window seat again",
    summary: "The same little table — cappuccino, journal.",
    emotionalTags: ["peaceful", "routine", "solo"],
    privacyLevel: "private",
    imageUrl:
      "https://images.unsplash.com/photo-1511920170033-f8396924c10b?w=800&q=80",
    location: "Cafe near class, Florence",
    userNote: "Being alone did not feel lonely today.",
  },
  {
    id: "sig-sun-routine-cafe",
    type: "routine",
    timestamp: "2026-02-23T20:30:00Z",
    source: "pattern detected",
    title: "Cafe after class ritual",
    summary: "Three visits to the cafe near class this week.",
    emotionalTags: ["routine", "peaceful"],
    privacyLevel: "private",
    routineName: "Cafe after class",
    evidence: [
      "sig-mon-place-cafe",
      "sig-mon-photo-cafe",
      "sig-sun-place-cafe-3",
    ],
    frequency: "three times this week",
    suggestion: "Want me to save this as a ritual?",
  },
  {
    id: "sig-tue-place-cafe-2",
    type: "place_visit",
    timestamp: "2026-02-18T15:30:00Z",
    source: "manual check-in",
    title: "Cafe near class",
    summary: "Second visit — journal and cappuccino.",
    emotionalTags: ["routine", "peaceful", "solo"],
    privacyLevel: "private",
    placeName: "Cafe near class",
    location: "Florence",
    durationMinutes: 45,
    tags: ["after class"],
    userSaved: true,
  },
  {
    id: "sig-thu-place-arno-2",
    type: "place_visit",
    timestamp: "2026-02-20T17:00:00Z",
    source: "manual check-in",
    title: "Arno river walk",
    summary: "Earlier Arno walk before Friday's golden hour.",
    emotionalTags: ["peaceful"],
    privacyLevel: "private",
    placeName: "Arno river walk",
    location: "Florence",
    durationMinutes: 35,
    tags: ["walk"],
    userSaved: true,
  },
];
